"""Information collection tool interfaces and adapters."""

from api.services.info_collection.contracts import (
    CopywritingRequest,
    CopywritingResult,
    CopywritingTool,
    DetailRequest,
    DetailResult,
    DetailTool,
    ScanRequest,
    ScanResult,
    ScanTool,
    ProfileRequest,
    ProfileResult,
    ProfileTool,
    ProbeRequest,
    ProbeResult,
    ProbeTool,
    SearchRequest,
    SearchResult,
    SearchTool,
    TagRequest,
    TagResult,
    TaggingTool,
)
from api.services.info_collection.factory import (
    DouyinToolset,
    InfoCollectionToolFactory,
    UrlToolset,
    XhsToolset,
)
from api.services.info_collection.streaming import (
    StreamStageSpec,
    make_stream_items,
    run_stream_pipeline,
    stream_stage,
)
from api.services.info_collection.xhs_stages import (
    XhsDetailStage,
    XhsNoteTaggingPersistStage,
    XhsPrefetchedDetailTaggingStage,
    XhsSearchStage,
    XhsTaggingStage,
)

__all__ = [
    "CopywritingRequest",
    "CopywritingResult",
    "CopywritingTool",
    "DetailRequest",
    "DetailResult",
    "DetailTool",
    "ScanRequest",
    "ScanResult",
    "ScanTool",
    "ProfileRequest",
    "ProfileResult",
    "ProfileTool",
    "ProbeRequest",
    "ProbeResult",
    "ProbeTool",
    "SearchRequest",
    "SearchResult",
    "SearchTool",
    "TagRequest",
    "TagResult",
    "TaggingTool",
    "InfoCollectionToolFactory",
    "DouyinToolset",
    "UrlToolset",
    "XhsToolset",
    "StreamStageSpec",
    "make_stream_items",
    "run_stream_pipeline",
    "stream_stage",
    "XhsDetailStage",
    "XhsNoteTaggingPersistStage",
    "XhsPrefetchedDetailTaggingStage",
    "XhsSearchStage",
    "XhsTaggingStage",
]
